# Site settings
baseurl = "http://example.org/"
languageCode = "en-us"
title = "Hugrid - Grid Theme For Hugo"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "McGill Robotics AUV Hub"
    subtitle = "All relevant links and resources in one place!"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Get the theme"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
